modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/qyl27/Higanbana/issues"
license = "MIT"

[[mods]]
modId = "higanbana"
version = "${mod_version}"
displayName = "Higanbana"
authors = "qyl27"
description = '''
Immortal friendship.
'''
#logoFile = ""

[[dependencies.higanbana]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.higanbana]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.higanbana]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_api_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.higanbana]]
modId = "smartbrainlib"
type = "required"
versionRange = "[${smart_brain_lib_version},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "higanbana.mixins.json"
