modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/qyl27/Higanbana/issues"
license = "MIT"

[[mods]]
modId = "higanbana"
version = "${version}"
displayName = "Higanbana"
authors = "qyl27"
description = '''
Immortal friendship.
'''
#logoFile = ""

[[dependencies.higanbana]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.higanbana]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.higanbana]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "higanbana.mixins.json"
